version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slpu_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: shortlink
    environment:
      POSTGRES_DB: localhosts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pqowie
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
